// Code generated by entc, DO NOT EDIT.

package ent

import (
	"com.enesuysal/go-chat/api/ent/schema"
	"com.enesuysal/go-chat/api/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescSurname is the schema descriptor for surname field.
	userDescSurname := userFields[2].Descriptor()
	// user.DefaultSurname holds the default value on creation for the surname field.
	user.DefaultSurname = userDescSurname.Default.(string)
}
